

service: whichflower 

provider:
  name: aws
  runtime: nodejs8.10

functions:
  which_flower:
    handler: handler.whichflower
    events:
      - http:
          path: /whichflower
          method: post
          cors: true
plugins:
  - serverless-offline